;;; Automatically generated by `recentf' on Tue Feb 11 12:09:56 2014.

(setq recentf-list
      '(
        "/Users/shevaunc/.ido.last"
        "/Users/shevaunc/Library/Preferences/Aquamacs Emacs/Preferences.el"
        "/Users/shevaunc/.emacs.bmk"
        "/Users/shevaunc/Library/Application Support/Aquamacs Emacs/haml-mode.el"
        "/Users/shevaunc/Library/Application Support/Aquamacs Emacs/elpa/archives/gnu/archive-contents"
        "/Users/shevaunc/Library/Application Support/Aquamacs Emacs/elpa/archives/marmalade/archive-contents"
        "/Users/shevaunc/Library/Application Support/Aquamacs Emacs/elpa/archives/elpa/archive-contents"
        "/Users/shevaunc/Library/Application Support/Aquamacs Emacs/sass-mode.el"
        "/Users/shevaunc/src/ibsa/fm_admin/app/assets/stylesheets/base_rate.css.scss"
        "/Users/shevaunc/src/ibsa/fm_admin/db/schema.rb"
        "/Users/shevaunc/src/ibsa/fm_admin/config/newrelic.yml"
        "/Users/shevaunc/src/ibsa/fm_admin/config.ru"
        "/Users/shevaunc/src/ibsa/fm_trb_bfs/project/spec/models/finance_application/finance_application_spec.rb"
        "/Users/shevaunc/src/ibsa/fm_trb_bfs/project/spec/model_overrides_for_blueprints.rb"
        "/Users/shevaunc/src/ibsa/fm_trb_bfs/project/Gemfile.lock"
        "/Users/shevaunc/src/ibsa/fm_trb_bfs/project/Gemfile"
        "/Users/shevaunc/src/ibsa/fm_trb_bfs/project/config/preinitializer.rb"
        "/Users/shevaunc/src/ibsa/fm_trb_bfs/project/config/boot.rb"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
